/**
 * SimulationAnalysis Component
 * LLM-powered deep content analysis of simulation logs with markdown rendering
 */
import { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { analyzeSimulation } from '../../utils/api';
import type { LLMSettings } from '../../types/simulation';

interface SimulationAnalysisProps {
  simulationId: string | null;
  logFilename: string | null;
  llmSettings?: LLMSettings;
  cachedAnalysis?: any;
  onAnalysisComplete?: (analysis: any) => void;
}

export default function SimulationAnalysis({ simulationId: propSimulationId, logFilename, llmSettings, cachedAnalysis, onAnalysisComplete }: SimulationAnalysisProps) {
  const [analyzing, setAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<any>(cachedAnalysis || null);
  const [error, setError] = useState<string | null>(null);
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    executive_summary: true,
    timeline: true,
    team_effectiveness: true,
    insights: true,
    recommendations: true,
  });

  const extractSimulationId = (filename: string): string | null => {
    const match = filename.match(/^(\d{8}_\d{6})_/);
    return match ? match[1] : null;
  };

  const simulationId = propSimulationId || (logFilename ? extractSimulationId(logFilename) : null);

  useEffect(() => {
    if (cachedAnalysis) {
      setAnalysis(cachedAnalysis);
    }
  }, [cachedAnalysis]);

  useEffect(() => {
    setAnalysis(cachedAnalysis || null);
    setError(null);
    setAnalyzing(false);
  }, [propSimulationId, logFilename]);

  const handleAnalyze = async () => {
    if (!simulationId) {
      setError('No simulation ID available');
      return;
    }

    setAnalyzing(true);
    setError(null);
    setAnalysis(null);

    try {
      const result = await analyzeSimulation(simulationId, llmSettings);
      setAnalysis(result.analysis);
      onAnalysisComplete?.(result.analysis);
    } catch (err: any) {
      setError(err.message || 'Failed to analyze simulation');
    } finally {
      setAnalyzing(false);
    }
  };

  const toggleSection = (section: string) => {
    setExpandedSections(prev => ({ ...prev, [section]: !prev[section] }));
  };

  const buildMarkdownReport = (): string => {
    if (!analysis) return '';
    const parts: string[] = [];
    parts.push('# Simulation Analysis Report\n');
    if (analysis.metadata) {
      if (analysis.metadata.premise) parts.push(`**Premise:** ${analysis.metadata.premise}\n`);
      parts.push(`**Analysis Date:** ${analysis.analysis_date || 'N/A'}\n`);
    }
    parts.push('\n## Executive Summary\n');
    parts.push(analysis.executive_summary || '');
    if (analysis.timeline?.length > 0) {
      parts.push('\n\n## Timeline of Events\n');
      analysis.timeline.slice(0, 20).forEach((event: any) => {
        parts.push(`\n**Step ${event.step}:** ${event.summary}`);
      });
    }
    parts.push('\n\n## Agent Analysis\n');
    parts.push(analysis.team_effectiveness?.analysis || '');
    parts.push('\n\n## Key Insights\n');
    parts.push(analysis.insights?.analysis || '');
    parts.push('\n\n## Recommendations\n');
    parts.push(analysis.recommendations?.recommendations || '');
    parts.push('\n\n---\n*Report generated by Concordia Simulation Analyzer*');
    return parts.join('\n');
  };

  const handleSaveToFile = () => {
    const markdown = buildMarkdownReport();
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    a.download = `simulation_analysis_${timestamp}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const markdownComponents = {
    h1: ({ children, ...props }: any) => <h1 className="text-2xl font-bold text-gray-900 mt-6 mb-3 pb-2 border-b border-gray-200" {...props}>{children}</h1>,
    h2: ({ children, ...props }: any) => <h2 className="text-xl font-bold text-gray-900 mt-5 mb-2" {...props}>{children}</h2>,
    h3: ({ children, ...props }: any) => <h3 className="text-lg font-semibold text-gray-800 mt-4 mb-2" {...props}>{children}</h3>,
    h4: ({ children, ...props }: any) => <h4 className="text-base font-semibold text-gray-800 mt-3 mb-1" {...props}>{children}</h4>,
    p: ({ children, ...props }: any) => <p className="text-sm text-gray-700 leading-relaxed my-2" {...props}>{children}</p>,
    ul: ({ children, ...props }: any) => <ul className="list-disc list-outside ml-5 space-y-1 my-2" {...props}>{children}</ul>,
    ol: ({ children, ...props }: any) => <ol className="list-decimal list-outside ml-5 space-y-1 my-2" {...props}>{children}</ol>,
    li: ({ children, ...props }: any) => <li className="text-sm text-gray-700 leading-relaxed" {...props}>{children}</li>,
    strong: ({ children, ...props }: any) => <strong className="font-semibold text-gray-900" {...props}>{children}</strong>,
    em: ({ children, ...props }: any) => <em className="italic text-gray-600" {...props}>{children}</em>,
    hr: (props: any) => <hr className="my-4 border-gray-200" {...props} />,
    blockquote: ({ children, ...props }: any) => <blockquote className="border-l-4 border-purple-300 pl-4 py-1 my-3 bg-purple-50 rounded-r" {...props}>{children}</blockquote>,
    table: ({ children, ...props }: any) => (
      <div className="overflow-x-auto my-4">
        <table className="min-w-full divide-y divide-gray-200 border border-gray-200 rounded-lg text-sm" {...props}>{children}</table>
      </div>
    ),
    thead: ({ children, ...props }: any) => <thead className="bg-gray-50" {...props}>{children}</thead>,
    th: ({ children, ...props }: any) => <th className="px-4 py-2 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider border-b border-gray-200" {...props}>{children}</th>,
    td: ({ children, ...props }: any) => <td className="px-4 py-2 text-sm text-gray-700 border-b border-gray-100" {...props}>{children}</td>,
    tr: ({ children, ...props }: any) => <tr className="hover:bg-gray-50" {...props}>{children}</tr>,
    code: ({ children, className, ...props }: any) => {
      const isInline = !className;
      return isInline
        ? <code className="bg-gray-100 text-purple-700 px-1.5 py-0.5 rounded text-xs font-mono" {...props}>{children}</code>
        : <code className={`block bg-gray-50 p-3 rounded-lg text-xs font-mono overflow-x-auto ${className || ''}`} {...props}>{children}</code>;
    },
  };

  const SectionHeader = ({ id, title, icon, color }: { id: string; title: string; icon: React.ReactNode; color: string }) => (
    <button
      onClick={() => toggleSection(id)}
      className={`w-full px-6 py-4 border-b border-gray-200 flex items-center justify-between ${color} hover:opacity-90 transition-opacity`}
    >
      <h3 className="text-lg font-semibold text-gray-900 flex items-center">
        {icon}
        {title}
      </h3>
      <svg className={`w-5 h-5 text-gray-500 transition-transform ${expandedSections[id] ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
      </svg>
    </button>
  );

  if (!simulationId) {
    return (
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 text-center">
        <svg className="mx-auto h-12 w-12 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
        </svg>
        <h3 className="mt-4 text-lg font-medium text-gray-900">No Simulation Loaded</h3>
        <p className="mt-2 text-sm text-gray-500">
          Load a simulation log to view LLM-powered analysis
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Analyze Button */}
      {!analysis && !analyzing && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <div className="text-center">
            <svg className="mx-auto h-12 w-12 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
            </svg>
            <h3 className="mt-4 text-lg font-medium text-gray-900">LLM-Powered Simulation Analysis</h3>
            <p className="mt-2 text-sm text-gray-500 mb-6">
              Generate comprehensive analysis including executive summary, per-agent goal attainment, psychological component effects, emergent dynamics, and research recommendations
            </p>
            <button
              onClick={handleAnalyze}
              className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500"
            >
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
              Analyze Simulation
            </button>
            <p className="mt-3 text-xs text-gray-400">
              This may take several minutes depending on simulation complexity
            </p>
          </div>
        </div>
      )}

      {/* Loading State */}
      {analyzing && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8">
          <div className="flex flex-col items-center justify-center">
            <div className="relative">
              <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-purple-500"></div>
              <div className="absolute top-0 left-0 h-16 w-16 rounded-full border-t-2 border-b-2 border-purple-300 animate-pulse"></div>
            </div>
            <h3 className="mt-6 text-lg font-medium text-gray-900">Analyzing Simulation...</h3>
            <p className="mt-2 text-sm text-gray-500 text-center max-w-md">
              Using LLM to generate comprehensive analysis. This includes parsing the simulation log, extracting events, analyzing team effectiveness, and generating recommendations.
            </p>
            <div className="mt-6 flex items-center space-x-4 text-xs text-gray-400">
              <div className="flex items-center">
                <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                3-5 minutes typical
              </div>
              <div className="flex items-center">
                <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
                AI-powered
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Error State */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-6">
          <div className="flex">
            <div className="flex-shrink-0">
              <svg className="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
              </svg>
            </div>
            <div className="ml-3">
              <h3 className="text-sm font-medium text-red-800">Analysis Failed</h3>
              <p className="mt-1 text-sm text-red-700">{error}</p>
              <button
                onClick={handleAnalyze}
                className="mt-3 text-sm font-medium text-red-800 hover:text-red-700 underline"
              >
                Try again
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Analysis Results */}
      {analysis && (
        <div className="space-y-6">
          {/* Action Bar */}
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-semibold text-gray-900">Analysis Report</h2>
            <div className="flex items-center gap-2">
              <button
                onClick={handleSaveToFile}
                className="inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Save Report
              </button>
              <button
                onClick={() => {
                  setAnalysis(null);
                  setError(null);
                  onAnalysisComplete?.(null);
                }}
                className="inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
                Re-analyze
              </button>
            </div>
          </div>

          {/* Executive Summary */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <SectionHeader
              id="executive_summary"
              title="Executive Summary"
              color="bg-gradient-to-r from-purple-50 to-pink-50"
              icon={<svg className="w-5 h-5 mr-2 text-purple-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}
            />
            {expandedSections.executive_summary && (
              <div className="px-6 py-4">
                <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                  {analysis.executive_summary || ''}
                </ReactMarkdown>
              </div>
            )}
          </div>

          {/* Timeline */}
          {analysis.timeline && analysis.timeline.length > 0 && (
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <SectionHeader
                id="timeline"
                title="Timeline of Events"
                color="bg-white"
                icon={<svg className="w-5 h-5 mr-2 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}
              />
              {expandedSections.timeline && (
                <div className="px-6 py-4 space-y-4 max-h-96 overflow-y-auto">
                  {analysis.timeline.slice(0, 15).map((event: any) => (
                    <div key={event.step} className="flex items-start">
                      <div className="flex-shrink-0 w-16 text-sm font-medium text-blue-600">
                        Step {event.step}
                      </div>
                      <div className="flex-1 text-sm text-gray-700">{event.summary}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Agent Analysis */}
          {analysis.team_effectiveness && (
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <SectionHeader
                id="team_effectiveness"
                title="Agent Analysis"
                color="bg-white"
                icon={<svg className="w-5 h-5 mr-2 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>}
              />
              {expandedSections.team_effectiveness && (
                <div className="px-6 py-4">
                  <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                    {analysis.team_effectiveness.analysis || ''}
                  </ReactMarkdown>
                </div>
              )}
            </div>
          )}

          {/* Key Insights */}
          {analysis.insights && (
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <SectionHeader
                id="insights"
                title="Key Insights"
                color="bg-white"
                icon={<svg className="w-5 h-5 mr-2 text-yellow-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg>}
              />
              {expandedSections.insights && (
                <div className="px-6 py-4">
                  <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                    {analysis.insights.analysis || ''}
                  </ReactMarkdown>
                </div>
              )}
            </div>
          )}

          {/* Recommendations */}
          {analysis.recommendations && (
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <SectionHeader
                id="recommendations"
                title="Recommendations"
                color="bg-white"
                icon={<svg className="w-5 h-5 mr-2 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" /></svg>}
              />
              {expandedSections.recommendations && (
                <div className="px-6 py-4">
                  <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                    {analysis.recommendations.recommendations || ''}
                  </ReactMarkdown>
                </div>
              )}
            </div>
          )}

          {/* Metadata */}
          {analysis.metadata && (
            <div className="bg-gray-50 rounded-lg p-4 text-xs text-gray-500">
              <div className="flex items-center justify-between">
                <span>Analyzed: {analysis.analysis_date}</span>
                <span>Simulation ID: {simulationId}</span>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
